version: "3.4"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
