[tool.poetry]
name = "transactions"
version = "0.1.0"
description = "An app to store and serve my personal transactions"
authors = ["martinabeleda <martin.abeleda@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.1"
flask = "^1.1.2"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
transactions = "transactions.console:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
