name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.0.5
          poetry install --no-interaction
      - name: Check formatting
        run: poetry run black --line-length 120 --check .
      - name: Code Quality
        run: poetry run pylint --rcfile .pylintrc clover tests
      - name: Run tests and generate coverage report
        run: poetry run pytest -s --cov=./ --cov-report=xml .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
